### ISSUE TITLE
Discrepancy manifestations valueset

### ISSUE THREAD

**Issue by annabel-uzl** [hl7-be/allergy#117]
Hi
The list of manifestations on https://www.caresetsbelgium.org/allergy-intolerance (word document with business rules) is different from the list of manifestations here https://www.ehealth.fgov.be/standards/fhir/allergy/1.0.1/ValueSet-be-riskmanifestation.html

Can this be put in sync? Which one is the most correct one? (I assume https://www.ehealth.fgov.be/standards/fhir/allergy/1.0.1/ValueSet-be-riskmanifestation.html)

**Comment by KarlienHL7Belgium** [comment]
The website https://www.caresetsbelgium.org/allergy-intolerance is not a good reference (this is taken care of) as the links are not updated on a frequent basis.
The BE FHIR terminology server should be available in the future (2025 TBC) in order to avoid using lists.
The best source of truth is the refset in the BE-extension and https://www.ehealth.fgov.be/standards/fhir/allergy/1.0.1/ValueSet-be-riskmanifestation.html 
A list can be outdated from one day to another, there is no guarantee on the content of the valuelist being uptodate. Currently the IG has the right list. 
Vitalink has its own FHIR terminology server that is aligned with the BE terminology edition. But currently the BE edition is available through the int'l FHIR terminology service.
These are facets you need to take into account up until the BE FHIR terminology server is up and running.
